### ISSUE TITLE
The .tres file doesn't appear when I click on "Make font"

### ISSUE THREAD

**Issue by BlueProgrammer212** [Raadiolained/BitmapFontMaker#2]
![image](https://user-images.githubusercontent.com/87359245/125408934-ff01e280-e3ed-11eb-94fd-0d051f5de4af.png)
When I press make font the .tres file doesnt appear. in the file system. Is that normal or is that a glitch?

**Comment by BlueProgrammer212** [comment]
Maybe something got obsolete or maybe its incompatible with my computer but like I'm Windows 10 that's compatible right?

**Comment by Raadiolained** [comment]
Hello,

I tested it with latest version of Godot (3.3.2) and everything seems to work.
In your screenshot I see the asset name to be created is with .tr extension, but it should be .tres, otherwise asset is not created.

**Comment by BlueProgrammer212** [comment]
Oh now it works thanks!
